<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="xmlschema"?>
<package format="3">
  <name>inspector_bringup</name>
  <version>0.1.0</version>
  <description>Bringup scripts and gazebo launch integration for Industrial Inspector</description>
  <maintainer email="nihara@example.com">Nihara Randini</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>inspector_description</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
