<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="xmlschema"?>
<package format="3">
  <name>inspector_description</name>
  <version>0.1.0</version>
  <description>URDF description and 3D assets for Autonomous Industrial Inspector</description>
  <maintainer email="nihara@example.com">Nihara Randini</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
